### ISSUE TITLE
Mapping different id between host & lxc

### ISSUE THREAD

**Issue by Jas0n99** [ddimick/proxmox-lxc-idmapper#1]
Just a feature request. This script would be a million times more helpful if it was able to handle mapping a different ID between the host & container.

**Comment by ddimick** [comment]
I thought about it a little bit but couldn't figure out a good way to accept user input for this. PRs are welcome if you want to take a pass at it, even if incomplete.

**Comment by Jas0n99** [comment]
Expanding on your current method of using: `uid[:gid]`

You could do `uid[:gid]=uid[:gid]` (equal with no space) to map a container ID to a different host ID.

Likewise, you could do `uid[:gid]-uid[:gid]` (dash with no spaces) to denote mass (standard) remapping a contiguous range. (Not sure this would get used much, most people just remap a few specific IDs).

My python is horrible (I usually have to spend a lot of time googling just to make small edits), otherwise I would submit some code.

**Comment by aurrak** [comment]
Looks like this is taken care of by this [PR](https://github.com/ddimick/proxmox-lxc-idmapper/pull/4).
